// File generated by FlutterFire CLI.
// This file will be auto-generated when you run: flutterfire configure
// For now, this is a placeholder. You need to:
// 1. Install Firebase CLI: npm install -g firebase-tools
// 2. Install FlutterFire CLI: dart pub global activate flutterfire_cli
// 3. Run: flutterfire configure
// This will create proper Firebase configuration for your project

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for GTR App
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC112psoZFM4KiZGQpS2M_IYiOy11eZ7nY',
    appId: '1:943186296997:web:c41ec81b4a33b0bf474d4c',
    messagingSenderId: '943186296997',
    projectId: 'gtr-app-1a18f',
    authDomain: 'gtr-app-1a18f.firebaseapp.com',
    storageBucket: 'gtr-app-1a18f.firebasestorage.app',
    measurementId: 'G-28ZZ9G3JZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTcCsZOuZRHWNHWzHVYjvKGLw_aJ26r3k',
    appId: '1:943186296997:android:371d4fcac5ce3c7e474d4c',
    messagingSenderId: '943186296997',
    projectId: 'gtr-app-1a18f',
    storageBucket: 'gtr-app-1a18f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1qi_kHP1yIU-Dfq-l5yfzRy2JTRsJV_A',
    appId: '1:943186296997:ios:6bb2e2b8ea3b5a43474d4c',
    messagingSenderId: '943186296997',
    projectId: 'gtr-app-1a18f',
    storageBucket: 'gtr-app-1a18f.firebasestorage.app',
    iosBundleId: 'com.example.gtrApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1qi_kHP1yIU-Dfq-l5yfzRy2JTRsJV_A',
    appId: '1:943186296997:ios:6bb2e2b8ea3b5a43474d4c',
    messagingSenderId: '943186296997',
    projectId: 'gtr-app-1a18f',
    storageBucket: 'gtr-app-1a18f.firebasestorage.app',
    iosBundleId: 'com.example.gtrApp',
  );
}
